---
version: '3.9'
services:
  zookeeper-old:
    image: confluentinc/cp-zookeeper:7.1.10
    hostname: zookeeper-old
    container_name: zookeeper-old
    ports:
      - "2183:2183"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2183
      ZOOKEEPER_TICK_TIME: 2000
    networks:
    - proxy_old_bridge_network

  broker-old:
    image: confluentinc/cp-server:7.1.10
    hostname: broker-old
    container_name: broker-old
    depends_on:
      - zookeeper-old
    networks:
    - proxy_old_bridge_network
    ports:
      - "9094:9094"
      - "9103:9103"
      - "8092:8092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-old:2183'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-old:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9103
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry-old:7086
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker-old:29094
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      CONFLUENT_HTTP_SERVER_LISTENERS: http://localhost:8092

  schema-registry-old:
    image: confluentinc/cp-schema-registry:7.1.10
    hostname: schema-registry-old
    container_name: schema-registry-old
    depends_on:
      - broker-old
    networks:
    - proxy_old_bridge_network
    ports:
      - "7086:7086"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry-old
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-old:29094'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:7086

  control-center-old:
    image: confluentinc/cp-enterprise-control-center:7.1.10
    hostname: control-center-old
    container_name: control-center-old
    depends_on:
      - broker-old
      - schema-registry-old
    networks:
    - proxy_old_bridge_network
    ports:
      - "9023:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker-old:29094'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry-old:7086"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021


  rest-proxy-old:
    image: confluentinc/cp-kafka-rest:7.1.10
    depends_on:
      - broker-old
      - schema-registry-old
    networks:
    - proxy_old_bridge_network
    ports:
      - 7082:7082
    hostname: rest-proxy-old
    container_name: rest-proxy-old
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy-old
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker-old:29094'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:7082"
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry-old:7086'


networks:
  proxy_old_bridge_network:
    name: data_service_network
    external: true
    # attachable: true